# Utilisez une image de base Python
FROM node:18

# Définissez le répertoire de travail dans le conteneur
WORKDIR /app

# Copiez le code de l'application Flask dans le conteneur
COPY . /app

# Installez les dépendances
RUN npm install

# TDD install mocha 
npm i -g mocha

